### ISSUE TITLE
[DataCap Application] Digital Earth Africa

### ISSUE THREAD

**Issue by techgood123** [a1991car/Allocator-Public-Data#1]
### Version

1

### DataCap Applicant

TechToolbox

### Project ID

004

### Data Owner Name

Digital Earth Africa

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.digitalearthafrica.org/

### Social Media Handle

https://www.digitalearthafrica.org/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

f1ijwcfm5ehqhi6xt4b7hyze53zsqqir3ndpwnk3i

### On-chain address for first allocation

512TiB

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TechToolbox is a technology services company that specializes in providing comprehensive solutions to our clients. We have a deep understanding of FILECOIN and excel at utilizing various tools to meet our clients' needs.

Our team consists of technical experts with extensive experience in the field. We recognize the significance of technology in modern business and are committed to delivering innovative and efficient solutions to our clients.

In the realm of FILECOIN, we are expert partners. We comprehend the working principles, potential, and application scenarios of FILECOIN, and we possess the expertise to optimize your FILECOIN experience using a wide range of tools and technologies.

Our services encompass a broad range of areas, including technology consulting, system integration, software development, and data analysis. Whether you are a startup or a well-established enterprise, we can provide customized solutions tailored to your specific requirements.

We prioritize our clients' success and work closely with them to ensure that our solutions help them achieve their business objectives. We are not just technology providers; we are collaborative partners dedicated to delivering excellence in technical services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Landsat scenes and metadata. DE Africa provides data from Landsat 5, 7 and 8 satellites, including historical observations dating back to late 1980s and regularly updated new acquisitions.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### Please share a sample of the data

```text
https://www.digitalearthafrica.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02951064, ZheJiang-JinHua
f02984282, HeNan-ZhengZhou
f0122215, ShanDong-QingDao
f0427989, ShanDong-QingDao
f02942808, GuangDong-ShenZhen
f02894875, JiangXi-FuZhou
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by a1991car** [comment]
If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

**Comment by techgood123** [comment]
@a1991car hey, We have been participate in Filecoin for three years and are familiar with data downloading, storage and maintenance. We are committed to finding precious data for Filecoin. USGS is a data website that stores 10PiB. The data of this website is not stored on the Filecoin network. We hope to be able to store USGS data on the Filecoin network.

**Comment by a1991car** [comment]
I tried to support you, but it seems that your F1 address and weekly quota were written incorrectly. Please close and reapply

**Comment by techgood123** [comment]
thanks for you telling me

**Comment by lyjmry** [comment]
checker:manualTrigger
