### ISSUE TITLE
[DataCap Application] LAMOST DR7

### ISSUE THREAD

**Issue by ssnks1** [a1991car/Allocator-Public-Data#14]
### Data Owner Name

LAMOST DR7

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

http://www.lamost.org/dr7/v2.0/

### Social Media Handle

http://www.lamost.org/dr7/v2.0/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

640TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1amlecro5w5dmz2kgdpqxhqojhrov3tt3sb2uaiq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Dear allocator, Filecoin Foundation and PL, I am a Filecoin enthusiast and technology geek. I do not belong to any company, but I have been working on the Filecoin network for two years. We are familiar with Filecoin technical principles and technical architecture, and are familiar with data storage and maintenance. With various major processes and DC experience, we are already downloading the data of LAMOST DR7.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Observed Plates：4,922 Total Spectra：10,431,197

Guoshoujing Telescope (the Large Sky Area Multi-Object Fiber Spectroscopic Telescope LAMOST) is a National Major Scientific Project built by the Chinese Academy of Sciences. Funding for the project has been provided by the National Development and Reform Commission. LAMOST is operated and managed by the National Astronomical Observatories, Chinese Academy of Sciences.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
http://www.lamost.org/dr7/v2.0/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03202108  HK
f03157905  GuangDong
f03157910  GuangDong
f09693     Sichuan
f03078786  Dongguan
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by a1991car** [comment]
How do you ensure the integrity and security of data are protected during preparation and transmission? Please describe any encryption, verification, or error checking measures you have taken during the data preparation process.

**Comment by ssnks1** [comment]
Ensuring the integrity and security of data during preparation and transmission is crucial. We will use secure transmission protocols, such as HTTPS and SFTP, to encrypt the content of data being transmitted over the network, preventing data from being stolen or tampered with. 

Additionally, we will encrypt data stored on hard drives to ensure that even if the physical media is stolen, the data cannot be accessed by unauthorized individuals. 

Before data transmission, we will generate hash values (such as SHA-256) and verify them at the receiving end to ensure that the data has not been modified during transmission. We will also calculate checksums during the data preparation process and validate them after transmission to detect any errors that may have occurred. 

Furthermore, we will record all data access and modification operations for subsequent auditing and tracking.

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger
