### ISSUE TITLE
[DataCap Application] NOAA

### ISSUE THREAD

**Issue by gimims** [a1991car/Allocator-Public-Data#16]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.noaa.gov/about-our-agency

### Social Media Handle

https://twitter.com/NOAA

### Social Media Type

Twitter

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

4PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1zdkarzmvihcfaxtilgmhotoxdmhs4q2ttwcwgjq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA is an agency that enriches life through science. Our reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them. I'm a DP with some experience of distribute data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NOAA has generated a multi-decadal reanalysis and reforecast data set to accompany the next-generation version of its ensemble prediction system, the Global Ensemble Forecast System, version 12 (GEFSv12).
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-gefs-reforecast/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03157883 GuangDong
f02828269 GuangDong
f02825282 HK
f03179570 sg
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by a1991car** [comment]
Given the significant scientific and public value of your dataset, how do you plan to monitor and ensure its long-term accessibility and stability on the Filecoin network? Please describe your data management and maintenance plan, including any backup and recovery strategies.

**Comment by gimims** [comment]
Ensuring the long-term accessibility and stability of the dataset on the Filecoin network is an important task. We will use data monitoring tools, such as Prometheus and Grafana, to track the status of data storage and access, and set up an alert system to promptly notify relevant personnel in case of data loss or access failure.

We will implement version control for the dataset to track changes and maintain a history. Detailed metadata will be maintained, including the data's source, format, creation date, and update logs to facilitate future searches and understanding.

We will focus on data backup by collaborating with more than four storage providers (SPs) and storing backups in different storage solutions, including local and cloud storage, to prevent single points of failure.

We will develop a detailed data recovery strategy, including Recovery Time Objectives (RTO) and Recovery Point Objectives (RPO).

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger
