### ISSUE TITLE
[DataCap Application] Digital Earth Africa

### ISSUE THREAD

**Issue by techgood123** [a1991car/Allocator-Public-Data#3]
### Version

1

### DataCap Applicant

TechToolbox

### Project ID

TechToolbox--004

### Data Owner Name

Digital Earth Africa 

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.digitalearthafrica.org/

### Social Media Handle

https://www.digitalearthafrica.org/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

512TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1fjdzd3l5fpcjt3z3hwutnblcub7xr6z6q2k2fpq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TechToolbox is a technology services company that specializes in providing comprehensive solutions to our clients. We have a deep understanding of FILECOIN and excel at utilizing various tools to meet our clients' needs.

Our team consists of technical experts with extensive experience in the field. We recognize the significance of technology in modern business and are committed to delivering innovative and efficient solutions to our clients.

In the realm of FILECOIN, we are expert partners. We comprehend the working principles, potential, and application scenarios of FILECOIN, and we possess the expertise to optimize your FILECOIN experience using a wide range of tools and technologies.

Our services encompass a broad range of areas, including technology consulting, system integration, software development, and data analysis. Whether you are a startup or a well-established enterprise, we can provide customized solutions tailored to your specific requirements.

We prioritize our clients' success and work closely with them to ensure that our solutions help them achieve their business objectives. We are not just technology providers; we are collaborative partners dedicated to delivering excellence in technical services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Landsat scenes and metadata. DE Africa provides data from Landsat 5, 7 and 8 satellites, including historical observations dating back to late 1980s and regularly updated new acquisitions.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We have been participate in Filecoin for three years and are familiar with data downloading, storage and maintenance. We are committed to finding precious data for Filecoin.
```

### Please share a sample of the data

```text
https://www.digitalearthafrica.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02951064, ZheJiang-JinHua
f02984282, HeNan-ZhengZhou
f0122215, ShanDong-QingDao
f0427989, ShanDong-QingDao
f02942808, GuangDong-ShenZhen
f02894875, JiangXi-FuZhou
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by techgood123** [comment]
We have resubmitted and look forward to your approval. @a1991car

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
![a6c22ce3ddd6cf13e614efbe1cd551b](https://github.com/a1991car/Allocator-Public-Data/assets/32447611/bbaa9693-85e7-4483-b367-e45893bb1f05)
![a3c6175aea6364b3a7ec8df0f3f29a8](https://github.com/a1991car/Allocator-Public-Data/assets/32447611/92761f10-450c-4558-8277-477b22dfd961)
![116746e204c712a623c7e642a97ab45](https://github.com/a1991car/Allocator-Public-Data/assets/32447611/cfade26e-262e-4087-b5c8-f11dcc8c28d2)
![28dd36040bbdd575dfe16b4b6796071](https://github.com/a1991car/Allocator-Public-Data/assets/32447611/582ac48e-8db4-43f9-9e5d-fcc800752f4c)
Everything looks good, so I will support it again and keep an eye on it

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by techgood123** [comment]
It seems that the data has not been updated, and the retrieval of most nodes has not been included in the spark system, but the SP we cooperate with can be retrieved. please help us

**Comment by techgood123** [comment]
![f3cd685f2d7681c25e015ab23f254f5f](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/f0f7ff0a-02d8-47a3-83fb-562309ac1ec6)
![da985adff68bb338508eec4d4cfe4ddb](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/d22735ec-8278-4a30-8e0d-24e3a64666e7)
![0aa758d2e9f1b58e3a353254cd54646d](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/4c8a5b3c-28e4-4c87-a546-db825714e5c8)
![79b6cacdf0b94c7b3111f2d84c6120cc](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/b10d4e82-4313-425d-8f66-ee4d6b270fb5)
![142d7424f8f03823c97548ae1f22dc09](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/4b388802-c2e9-47c4-8ec8-8169816d2cb9)
![f72c4b3b049cb81ae7dd33998a1641d0](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/838d0a9d-4693-43d5-b9b1-a955e3fef04e)
![182c1fe439be67156772b106134544eb](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/c1d46f55-71c1-4053-8cee-cb2d31b01547)
![92226356076ffbddc2ea85c94dfe4d66](https://github.com/a1991car/Allocator-Public-Data/assets/127367768/deebbb95-de20-4676-a3a0-11122c65e40e)

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
Too much time has passed and the applicant has no new needs. Close this issue.
